#!/bin/sh -eu
old_version="$1"
new_version="$2"
sed -i '' "s/version = \"$old_version\"/version = \"$new_version\"/g" Cargo.toml
cargo update

git add Cargo.toml
git add Cargo.lock

git commit -m "Update version to $new_version"